### ISSUE TITLE
Stripping data-* attributes

### ISSUE THREAD

**Issue by zgohr** [excieve/mezzanine-wymeditor#1] opened 2013-07-17 13:59 UTC
Switching from TinyMCE with all of Mezzanine's filtering turned off. Saving pages with Wymeditor seems to strip the `data-` attributes from HTML and I can't quite pin it down. According to wymeditor's XhtmlValidator, these attributes should be left alone.

```
> WYMeditor.XhtmlValidator._attributes.core.attributes
["class", "id", "style", "title", "accesskey", "tabindex", "/^data-.*/"]
```

**Comment by excieve** [comment] 2013-07-17 18:32
Sorry, I can't reproduce this with `RICHTEXT_FILTER_LEVEL = 3` in my settings - `data-*` attributes are preserved for me in this case. Can you try to setup fresh Mezzanine app with mezzanine-wymeditor and see if it still happens? Maybe something else gets in the way.

**Comment by zgohr** [comment] 2013-07-17 20:34
Looks to be getting removed somewhere in Wymeditor's parser/lexer code. I created a brand new mezzanine project using the `mezzanine-project` command (yes to add default content,) added the app in `INSTALLED_APPS`, set `RICHTEXT_WIDGET_CLASS`, turned off filtering in admin/site/settings.

Logged into admin, went to the "/about" page and clicked "Edit." Open up the HTML view (html toggle button,) changed to `<p data-bs>About us</p>`. Click the HTML toggle button once to close, and again to open and `data-bs` is magically gone from the tag.

**Comment by excieve** [comment] 2013-07-17 21:01
OK, `data-bs` doesn't work for me either while `data-bs="bs"` works. In fact this happens with any attribute. I guess it filters out all empty attributes.

**Comment by zgohr** [comment] 2013-07-17 21:06
It seems empty tags as well, `<div></div>`. Ideas? Or is this something we live with?

**Comment by excieve** [comment] 2013-07-17 21:57
There's an issue open in WYMeditor github to support empty tags: https://github.com/wymeditor/wymeditor/issues/375

There's a sensible proposal to have a configurable list of tags that are allowed to be empty (or maybe just having a switch to disable that completely). I suppose it could be extended to attributes as well. Could you please pursue it there?

As a quick and dirty fix you can override `WYMEDITOR_SETUP_JS` with your own setup script and monkey-patch [this](https://github.com/wymeditor/wymeditor/blob/master/src/wymeditor/parser/xhtml-sax-listener.js#L199) to get rid of stripping empty tags. And for attributes somewhere [here](https://github.com/wymeditor/wymeditor/blob/master/src/wymeditor/parser/xhtml-validator.js#L691) if you really need this but surely it might bite later.

Closing this issue as it's really not something to be done in mezzanine-wymeditor.

**Closed as completed by excieve** 2013-07-17 21:57 UTC
Labels: wontfix

**Comment by zgohr** [comment] 2013-07-17 22:03
Thanks @excieve, appreciate your help on this.
